services:
  equipment-rent:
    container_name: equipment-rent
    build: .
    depends_on:
      rent-postgres:
        condition: service_healthy
      rent-mosquitto:
        condition: service_started
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - rent-network
    environment:
      - MQTT_BROKER_HOST=rent-mosquitto
      - MQTT_BROKER_PORT=1883
      - DATABASE_URL=postgres://rentdb:rentdb@rent-postgres:5432/rent
      - SECRET_KEY=ffc2c1bf196a3a3ebbfcf731f4b03fe57239c2e81be50bd23a36e472ef3913b2

  rent-postgres:
    image: postgres:16
    container_name: postgres-rentdb
    environment:
      POSTGRES_USER: "rentdb"
      POSTGRES_PASSWORD: "rentdb"
      POSTGRES_DB: "rent"
    volumes:
      - rentdb-data:/var/lib/postgresql/data
      - ./create-tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - rent-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rentdb -d rent"]
      interval: 5s
      timeout: 5s
      retries: 10

  rent-mosquitto:
    image: eclipse-mosquitto
    container_name: rent-mqtt5
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - rent-network

volumes:
  rentdb-data:

networks:
  rent-network:
    name: rent-network
    driver: bridge
